a=4
b=6
print(f"Addition: {a} + {b} = {a+b}")
print(f"Exponentian: {a} ** {b} = {a**b}")
print(f"Multiplication: {a} * {b} = {a*b}")
print(f"Division: {a} / {b} = {a/b}")
print(f"Modulus: {a} % {b} = {a%b}")
print(f"Floor division: {a} // {b} = {a//b}")
print(f"Subtraction: {a} - {b} = {a-b}")